// Generated by CoffeeScript 1.6.3
(function() {
  var Benchmark, evaluate, parse, _ref;

  Benchmark = require('benchmark');

  _ref = require('../lib/GoateeScript').GoateeScript, evaluate = _ref.evaluate, parse = _ref.parse;

  exports.GoateeScriptTest = {
    setUp: function(callback) {
      this.benchmark = new Benchmark.Suite;
      return callback();
    },
    'test can add two positive numbers': function(test) {
      test.equal(evaluate('1+1'), 2);
      return test.done();
    },
    'benchmark of adding two positive numbers': function(test) {
      this.benchmark.add('goatee-script  : 1+1', function() {
        return evaluate('1+1');
      }).add('javascript     : 1+1', function() {
        return 1 + 1;
      }).add('javascript eval: 1+1', function() {
        return eval('1+1');
      }).on('cycle', function(event) {
        return console.log(String(event.target));
      }).on('complete', function() {
        return console.log('Fastest is ' + this.filter('fastest').pluck('name'));
      }).run({
        async: false
      });
      return test.done();
    }
  };

}).call(this);

/*
//@ sourceMappingURL=GoateeScriptTest.map
*/
