// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>
© Copyright 2009-2013 Jeremy Ashkenas

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {
  var Command, Repl, VERSION, evaluate, exports, nomnom, render, spawn, _ref, _ref1;

  nomnom = require('nomnom');

  spawn = require('child_process').spawn;

  _ref = require('../GoateeScript').GoateeScript, VERSION = _ref.VERSION, render = _ref.render, evaluate = _ref.evaluate;

  Repl = require('./Repl').Repl;

  exports = (_ref1 = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref1 : this;

  exports.Command = Command = (function() {
    var execute, forkNode, optionParser, opts, parseOptions, printLine, printWarn, statements, version;

    function Command() {}

    printLine = function(line) {
      return process.stdout.write(line + '\n');
    };

    printWarn = function(line) {
      return process.stderr.write(line + '\n');
    };

    opts = {};

    statements = null;

    optionParser = null;

    parseOptions = function() {
      opts = nomnom.script('goatee-script').option('statements', {
        list: true,
        position: 0,
        help: 'string passed from the command line to evaluate'
      }).option('eval', {
        abbr: 'e',
        metavar: 'STATEMENT',
        list: true,
        help: 'string passed from the command line to evaluate'
      }).option('help', {
        abbr: 'h',
        flag: true,
        help: 'display this help message'
      }).option('interactive', {
        abbr: 'i',
        flag: true,
        help: 'run an interactive GoateeScript REPL'
      }).option('nodejs', {
        metavar: 'OPTION',
        list: true,
        help: 'pass one option directly to the "node" binary, repeat for muliple options'
      }).option('print', {
        abbr: 'p',
        flag: true,
        help: 'print out compiled GoateeScript'
      }).option('version', {
        abbr: 'v',
        flag: true,
        help: 'display the version number and exit'
      }).help('If called without options, `goatee-script` will run interactive.').parse();
      statements = [].concat(opts.statements != null ? opts.statements : []).concat(opts["eval"] != null ? opts["eval"] : []).join(';');
      opts["eval"] || (opts["eval"] = statements !== '');
    };

    forkNode = function() {
      return spawn(process.execPath, opts.nodejs, {
        cwd: process.cwd(),
        env: process.env,
        customFds: [0, 1, 2]
      });
    };

    version = function() {
      return printLine("GoateeScript version " + VERSION);
    };

    execute = function() {
      return printLine(opts.print ? render(statements) : evaluate(statements));
    };

    Command.run = function() {
      parseOptions();
      if (opts.nodejs) {
        return forkNode();
      }
      if (opts.version) {
        return version();
      }
      if (opts.interactive) {
        return Repl.start(opts);
      }
      if (opts["eval"]) {
        return execute();
      }
      return Repl.start(opts);
    };

    return Command;

  })();

}).call(this);

/*
//@ sourceMappingURL=Command.map
*/
