// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied. See the License for the specific language governing
permissions and limitations under the License.
*/


(function() {
  var Notator, exports, _ref;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.Notator = Notator = (function() {
    var unwrap, wrap;

    function Notator() {}

    Notator.unwrap = unwrap = /^function\s*\(\)\s*\{\s*return\s*([\s\S]*);\s*\}/;

    Notator.wrap = wrap = function(action) {
      return "(" + action + ".call(this))";
    };

    Notator.operation = Notator.o = function(pattern, action, options) {
      var match;
      if (!action) {
        return [pattern, '$$ = $1;', options];
      }
      action = (match = unwrap.exec(action)) ? match[1] : wrap(action);
      return [pattern, "$$ = " + action + ";", options];
    };

    Notator.resolve = Notator.r = function(pattern, action) {
      var match;
      if (pattern.source != null) {
        pattern = pattern.source;
      }
      if (!action) {
        return [pattern, 'return;'];
      }
      action = (match = unwrap.exec(action)) ? match[1] : wrap(action);
      return [pattern, "return " + action + ";"];
    };

    Notator.conditional = Notator.c = function(conditions, pattern, action) {
      return [conditions].concat(Notator.resolve(pattern, action));
    };

    return Notator;

  })();

}).call(this);

/*
//@ sourceMappingURL=Notator.map
*/
