// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com>
© Copyright 2009-2013 Jeremy Ashkenas

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {
  var Expression, NodeRepl, Repl, compile, evaluate, exports, fs, isArray, path, render, stringify, _ref, _ref1,
    __hasProp = {}.hasOwnProperty;

  fs = require('fs');

  path = require('path');

  NodeRepl = require('repl');

  _ref = require('../GoateeScript').GoateeScript, compile = _ref.compile, evaluate = _ref.evaluate, render = _ref.render, stringify = _ref.stringify;

  Expression = require('./Expression').Expression;

  isArray = require('./Utility').Utility.isArray;

  exports = (_ref1 = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref1 : this;

  exports.Repl = Repl = (function() {
    var _addHistory, _addMultilineHandler, _options, _prettyErrorMessage;

    function Repl() {}

    _prettyErrorMessage = function(error, filename, code, colorize) {
      var e, message, _i, _len;
      if ((error == null) || error === false || (isArray(error) && error.length === 0)) {
        return null;
      }
      if (isArray(error)) {
        message = [];
        for (_i = 0, _len = error.length; _i < _len; _i++) {
          e = error[_i];
          message.push(_prettyErrorMessage(e, filename, code, colorize));
        }
        return message.join("\n——\n");
      }
      filename = error.filename || filename;
      code = error.code || code;
      message = error.message;
      if (colorize != null) {
        if (colorize === true) {
          colorize = function(str) {
            return "\x1B[1;31m" + str +"\x1B[0m";
          };
        }
        message = colorize(message);
      }
      return "" + filename + ": " + message;
    };

    _addMultilineHandler = function(repl) {
      var inputStream, multiline, nodeLineListener, outputStream, rli;
      rli = repl.rli, inputStream = repl.inputStream, outputStream = repl.outputStream;
      multiline = {
        enabled: false,
        initialPrompt: repl.prompt.replace(/^[^> ]*/, function(x) {
          return x.replace(/./g, '-');
        }),
        prompt: repl.prompt.replace(/^[^> ]*>?/, function(x) {
          return x.replace(/./g, '.');
        }),
        buffer: ''
      };
      nodeLineListener = rli.listeners('line')[0];
      rli.removeListener('line', nodeLineListener);
      rli.on('line', function(cmd) {
        if (multiline.enabled) {
          multiline.buffer += "" + cmd + "\n";
          rli.setPrompt(multiline.prompt);
          rli.prompt(true);
        } else {
          nodeLineListener(cmd);
        }
      });
      return inputStream.on('keypress', function(char, key) {
        if (!(key && key.ctrl && !key.meta && !key.shift && key.name === 'v')) {
          return;
        }
        if (multiline.enabled) {
          if (!multiline.buffer.match(/\n/)) {
            multiline.enabled = !multiline.enabled;
            rli.setPrompt(repl.prompt);
            rli.prompt(true);
            return;
          }
          if ((rli.line != null) && !rli.line.match(/^\s*$/)) {
            return;
          }
          multiline.enabled = !multiline.enabled;
          rli.line = '';
          rli.cursor = 0;
          rli.output.cursorTo(0);
          rli.output.clearLine(1);
          multiline.buffer = multiline.buffer.replace(/\n/g, '\uFF00');
          rli.emit('line', multiline.buffer);
          multiline.buffer = '';
        } else {
          multiline.enabled = !multiline.enabled;
          rli.setPrompt(multiline.initialPrompt);
          rli.prompt(true);
        }
      });
    };

    _addHistory = function(repl, filename, maxSize) {
      var buffer, fd, lastLine, readFd, size, stat;
      lastLine = null;
      try {
        stat = fs.statSync(filename);
        size = Math.min(maxSize, stat.size);
        readFd = fs.openSync(filename, 'r');
        buffer = new Buffer(size);
        fs.readSync(readFd, buffer, 0, size, stat.size - size);
        repl.rli.history = buffer.toString().split('\n').reverse();
        if (stat.size > maxSize) {
          repl.rli.history.pop();
        }
        if (repl.rli.history[0] === '') {
          repl.rli.history.shift();
        }
        repl.rli.historyIndex = -1;
        lastLine = repl.rli.history[0];
      } catch (_error) {}
      fd = fs.openSync(filename, 'a');
      repl.rli.addListener('line', function(code) {
        if (code && code.length && code !== '.history' && lastLine !== code) {
          fs.write(fd, "" + code + "\n");
          return lastLine = code;
        }
      });
      repl.rli.on('exit', function() {
        return fs.close(fd);
      });
      return repl.commands['.history'] = {
        help: 'Show command history',
        action: function() {
          repl.outputStream.write("" + (repl.rli.history.slice(0).reverse().join('\n')) + "\n");
          return repl.displayPrompt();
        }
      };
    };

    Repl.defaults = _options = {
      context: {},
      variables: {},
      prompt: 'goatee> ',
      historyFile: process.env.HOME ? path.join(process.env.HOME, '.goatee_history') : void 0,
      historyMaxInputSize: 10240,
      "eval": function(input, context, filename, callback) {
        var error, output, variables;
        input = input.replace(/\uFF00/g, '\n');
        input = input.replace(/^\(([\s\S]*)\n\)$/m, '$1');
        context = _options.context || context;
        variables = _options.variables || (_options.variables = {});
        error = [];
        Expression.callback(function(expression, result, stack, errors) {
          var key, value, _ref2;
          context['_'] = result;
          _ref2 = stack.variables;
          for (key in _ref2) {
            if (!__hasProp.call(_ref2, key)) continue;
            value = _ref2[key];
            variables[key] = value;
          }
          if (errors != null) {
            error = error.concat(errors);
          }
        });
        try {
          output = (function() {
            switch (_options.flags.mode) {
              case 'c':
                return compile(input, null, _options.flags.compress);
              case 'p':
                return stringify(input, null, _options.flags.compress);
              case 'r':
                return render(input, null, _options.flags.compress);
              default:
                return evaluate(input, context, variables);
            }
          })();
          callback(_prettyErrorMessage(error, filename, input, true), output);
        } catch (_error) {
          error = _error;
          callback(_prettyErrorMessage(error, filename, input, true));
        }
      }
    };

    Repl.start = function(flags, options) {
      var major, minor, repl, _ref2;
      if (flags == null) {
        flags = {};
      }
      if (options == null) {
        options = _options;
      }
      _ref2 = process.versions.node.split('.').map(function(n) {
        return parseInt(n);
      }), major = _ref2[0], minor = _ref2[1];
      if (major === 0 && minor < 10) {
        console.warn("Node 0.10.0+ required for GoateeScript REPL");
        process.exit(1);
      }
      _options = options;
      _options.flags = flags;
      repl = NodeRepl.start(options);
      repl.on('exit', function() {
        return repl.outputStream.write('\n');
      });
      _addMultilineHandler(repl);
      if (options.historyFile) {
        _addHistory(repl, options.historyFile, options.historyMaxInputSize);
      }
      return repl;
    };

    return Repl;

  })();

}).call(this);

/*
//@ sourceMappingURL=Repl.map
*/
