// Generated by CoffeeScript 1.6.3
/*
© Copyright 2013 Stephan Jorek <stephan.jorek@gmail.com> /
© Copyright 2009-2013 Jeremy Ashkenas <https://github.com/jashkenas>

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {
  var Command, exports, nomnom, spawn, _ref;

  nomnom = require('nomnom');

  spawn = require('child_process').spawn;

  exports = (_ref = typeof module !== "undefined" && module !== null ? module.exports : void 0) != null ? _ref : this;

  exports.Command = Command = (function() {
    var opts, statements;

    opts = null;

    statements = null;

    function Command(command) {
      this.command = command != null ? command : require('./GoateeScript').GoateeScript;
    }

    Command.prototype.printLine = function(line) {
      return process.stdout.write(line + '\n');
    };

    Command.prototype.printWarn = function(line) {
      return process.stderr.write(line + '\n');
    };

    Command.prototype.parseOptions = function() {
      var shift_line;
      shift_line = "\n                                  ";
      opts = nomnom.script(this.command.NAME).option('statements', {
        list: true,
        type: 'string',
        position: 0,
        help: 'string passed from the command line to evaluate'
      }).option('run', {
        abbr: 'r',
        type: 'string',
        metavar: 'STATEMENT',
        list: true,
        help: "string passed from the command line to " + shift_line + " evaluate"
      }).option('help', {
        abbr: 'h',
        flag: true,
        help: "display this help message"
      }).option('interactive', {
        abbr: 'i',
        flag: true,
        help: "run an interactive `" + this.command.NAME + "` read-" + shift_line + " execute-print-loop (repl)"
      }).option('mode', {
        metavar: 'MODE',
        abbr: 'm',
        "default": 'eval',
        choices: ['compile', 'c', 'evaluate', 'eval', 'e', 'print', 'p', 'render', 'r', 'stringify', 'string', 's'],
        help: "[c]ompile, [e]valuate, [p]rint, [r]ender " + shift_line + " or [s]tringify statements, default:"
      }).option('compress', {
        abbr: 'c',
        flag: true,
        help: "compress the abstract syntax tree (ast)"
      }).option('nodejs', {
        metavar: 'OPTION',
        list: true,
        help: "pass one option directly to the 'node' " + shift_line + " binary, repeat for muliple options"
      }).option('version', {
        abbr: 'v',
        flag: true,
        help: "display the version number and exit"
      }).help("If called without options, `" + this.command.NAME + "` will run interactive.").parse();
      statements = [].concat(opts.statements != null ? opts.statements : []).concat(opts.run != null ? opts.run : []);
      opts.mode = opts.mode[0];
      opts.run || (opts.run = statements.length > 0);
      return statements = statements.join(';');
    };

    Command.prototype.forkNode = function() {
      return spawn(process.execPath, opts.nodejs, {
        cwd: process.cwd(),
        env: process.env,
        customFds: [0, 1, 2]
      });
    };

    Command.prototype.version = function() {
      return "" + this.command.NAME + " version " + this.command.VERSION;
    };

    Command.prototype.execute = function() {
      switch (opts.mode) {
        case 'compile':
        case 'c':
          return this.command.compile(statements, null, opts.compress);
        case 'print':
        case 'p':
          return this.command.stringify(statements, null, opts.compress);
        case 'render':
        case 'r':
          return this.command.render(statements, null, opts.compress);
        case 'stringify':
        case 'string':
        case 's':
          return JSON.stringify(this.command.evaluate(statements));
        case 'evaluate':
        case 'eval':
        case 'e':
          return this.command.evaluate(statements);
        default:
          throw new Error('Unknown execution-mode given.');
      }
    };

    Command.prototype.interactive = function(repl) {
      if (repl == null) {
        repl = require('./Repl').Repl;
      }
      return repl.start(this.command, opts);
    };

    Command.prototype.run = function() {
      this.parseOptions();
      if (opts.nodejs) {
        return this.forkNode();
      }
      if (opts.version) {
        return this.printLine(this.version());
      }
      if (opts.interactive) {
        return this.interactive();
      }
      if (opts.run) {
        return this.printLine(this.execute());
      }
      return this.interactive();
    };

    return Command;

  })();

}).call(this);

/*
//@ sourceMappingURL=Command.map
*/
